quarkus:

  http:
    root-path: /photobook-demo

  mongodb:
    connection-string: ${MONGODB_URL:mongodb://localhost:27017/photobook_demo}

  native:
    additional-build-args: -H:IncludeResources=build.properties