apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: quarkus-photobook-aot
spec:
  template:
    metadata:
      name: quarkus-photobook-aot-rev1
    spec:
      containers:
        - image: docker.io/fugeritorg/quarkus-photobook:latest-native
          ports:
            - containerPort: 8080
          env:
#            - name: MONGODB_URL
#              value: # setup mongo db url