FROM debian:bookworm-slim

WORKDIR /app

# Copy the native binary from the build stage
COPY target/quarkus-photobook*-runner /app/quarkus-photobook

# Run the application
ENTRYPOINT [ "sh", "-c", "/app/quarkus-photobook ${JAVA_OPTS_APPEND}"]